(ns pdb-snapshot
  "Generate a PDB spec EDN for `hive-gimp.pdb.native/defprocedures` from a
   live GIMP `describe`.

       clojure -M:pdb-snapshot resources/hive_gimp/pdb/starter.edn 9877 \\
         plug-in-despeckle:despeckle gimp-drawable-invert:invert-drawable \\
         file-png-export:export-png

   Each argument is `procedure` or `procedure:fn-name`. Writes the file only
   when every procedure was described; otherwise prints the refusal and
   exits 1."
  (:require [clojure.pprint :as pprint]
            [clojure.string :as str]
            [hive-gimp.pdb :as pdb]
            [hive-gimp.pdb.derive :as derive]
            [hive-gimp.response :as response]
            [hive-gimp.transport.socket :as socket]))

;; Copyright (C) 2026 Pedro Gomes Branquinho (BuddhiLW) <pedrogbranquinho@gmail.com>
;;
;; SPDX-License-Identifier: MIT

(defn parse-request
  "`\"proc:fn\"` -> {:procedure \"proc\" :fn 'fn}; `\"proc\"` -> {:procedure \"proc\"}."
  [s]
  (let [[procedure fn-name] (str/split s #":" 2)]
    (cond-> {:procedure procedure}
      (seq fn-name) (assoc :fn (symbol fn-name)))))

(defn snapshot
  "Specs for `requests`, described live through `target`. Answers
   `{:specs [...]}` or `{:failed outcome}` at the first refusal."
  [target requests]
  (reduce (fn [acc {:keys [procedure fn]}]
            (let [described (pdb/describe target procedure)]
              (if (response/ok? described)
                (update acc :specs conj
                        (derive/valid-spec
                         (cond-> (derive/info->spec (:value described))
                           fn (assoc :fn fn))))
                (reduced {:failed described}))))
          {:specs []}
          requests))

(defn render
  "The EDN text for `specs`, with a header naming its origin."
  [specs]
  (str ";; GENERATED by dev/pdb_snapshot.clj from a live GIMP describe.\n"
       ";; Regenerate rather than hand-edit; :fn names are the snapshot arguments.\n"
       (binding [pprint/*print-right-margin* 100
                 *print-namespace-maps* false]
         (with-out-str (pprint/pprint specs)))))

(defn -main
  [out port & requests]
  (let [target (socket/transport {:host "127.0.0.1" :port (parse-long port) :timeout-ms 60000} 3000)
        {:keys [specs failed]} (snapshot target (map parse-request requests))]
    (if failed
      (do (binding [*out* *err*] (prn failed)) (System/exit 1))
      (do (spit out (render specs))
          (println "wrote" (count specs) "spec(s) to" out)
          (shutdown-agents)))))
