(ns hive-di.hooks.macros
  "clj-kondo hooks for hive-di macros that generate vars."
  (:require [clj-kondo.hooks-api :as api]
            [clojure.string :as str]))

(defn- camel->kebab [s]
  (-> s
      (str/replace #"([a-z])([A-Z])" "$1-$2")
      str/lower-case))

(defn- token-like [node value]
  (with-meta (api/token-node value) (meta node)))

(defn- def-node [name-node]
  (api/list-node
   [(api/token-node 'def) name-node (api/map-node [])]))

(defn- defn-node [name-node arglists]
  (api/list-node
   (list* (api/token-node 'defn)
          name-node
          (map (fn [args]
                 (api/list-node
                  [(api/vector-node (mapv api/token-node args))
                   (api/token-node nil)]))
               arglists))))

(defn- do-node [nodes]
  (api/list-node (list* (api/token-node 'do) nodes)))

(defn defconfig
  "Register every var generated by defconfig and analyze field expressions."
  [{:keys [node]}]
  (let [[_ config-node & field-nodes] (:children node)
        config-name (api/sexpr config-node)
        base        (camel->kebab (name config-name))
        generated   [(def-node config-node)
                     (defn-node (token-like config-node (symbol base))
                                [['_variant] ['_variant '_data]])
                     (defn-node (token-like config-node (symbol (str base "?")))
                                [['_value]])
                     (defn-node (token-like config-node (symbol (str "->" base)))
                                [['_keyword]])
                     (def-node (token-like config-node
                                           (symbol (str config-name "-fields"))))
                     (def-node (token-like config-node
                                           (symbol (str config-name "-schema"))))
                     (defn-node (token-like config-node
                                            (symbol (str "resolve-" config-name)))
                                [[] ['_overrides] ['_overrides '_opts]])]
        uses        (do-node field-nodes)]
    {:node (do-node (conj generated uses))}))

(defn defmanifest
  "Register the manifest plus the two fixed helper functions it generates."
  [{:keys [node]}]
  (let [[_ name-node manifest-node] (:children node)]
    {:node (do-node
            [(def-node name-node)
             (defn-node (token-like name-node 'init!) [[]])
             (defn-node (token-like name-node 'registered-keys) [[]])
             (do-node [manifest-node])])}))

(defn defconfig-tests
  "Register the four generated test vars and analyze referenced config inputs."
  [{:keys [node]}]
  (let [[_ config-node & uses] (:children node)
        config-name (api/sexpr config-node)
        suffixes    ["-totality" "-defaults-only" "-roundtrip" "-field-mutations"]
        defs        (mapv (fn [suffix]
                            (def-node
                             (token-like config-node
                                         (symbol (str config-name suffix)))))
                          suffixes)]
    {:node (do-node (conj defs (do-node uses)))}))
