(ns hive-gimp.catalog-test
  "The command contract is generated by a script against someone else's source.
   `it parsed` is not the same as `it is usable`, so the shipped resource is
   asserted here rather than trusted."
  (:require [clojure.test :refer [deftest is testing]]
            [hive-gimp.catalog :as catalog]
            [hive-gimp.schema :as schema]
            [hive-gimp.contract :as contract]))

;; Copyright (C) 2026 Pedro Gomes Branquinho (BuddhiLW) <pedrogbranquinho@gmail.com>
;;
;; SPDX-License-Identifier: MIT

(deftest the-shipped-contract-conforms
  (is (empty? (catalog/invalid))
      (str "malformed descriptors: " (pr-str (take 3 (catalog/invalid))))))

(deftest the-contract-is-not-empty
  ;; A resource that failed to load produces an empty catalog and every command
  ;; then reports `unknown command`, which reads as a caller error.
  (is (< 50 (count (catalog/commands)))))

(deftest every-command-resolves-by-both-names
  (doseq [[command descriptor] (catalog/commands)]
    (is (= descriptor (catalog/descriptor command)))
    (is (some? (catalog/descriptor (:tool descriptor)))
        (str "tool name " (:tool descriptor) " must resolve"))))

(deftest wire-and-hive-names-agree-on-shape
  (doseq [descriptor (vals (catalog/commands))
          param (:params descriptor)]
    (is (= (:name param) (clojure.string/replace (:wire param) "_" "-"))
        (str "vocabulary drift in " (:command descriptor) "/" (:wire param)))))

(deftest no-parameter-is-both-required-and-defaulted
  (doseq [descriptor (vals (catalog/commands))
          param (:params descriptor)]
    (is (not (and (:required? param) (contains? param :default)))
        (str (:command descriptor) "/" (:name param)))))

;; =============================================================================
;; Collision handling
;; =============================================================================

(deftest a-collision-is-resolved-toward-the-canonical-claimant
  (testing "the reference server's check_server tool sends get_gimp_info, so two tools claim it"
    (let [descriptors [{:command "get_gimp_info" :tool "gimp_check_server"
                        :doc "borrowed for a connection probe" :params []}
                       {:command "get_gimp_info" :tool "gimp_get_gimp_info"
                        :doc "the real thing"
                        :params [{:name "verbose" :wire "verbose" :schema :boolean :default false}]}]
          indexed (contract/index descriptors)]
      (is (= "gimp_get_gimp_info" (:tool (get indexed "get_gimp_info")))
          "last-write-wins here would silently drop the parameter list"))))

(deftest a-collision-with-no-canonical-claimant-keeps-the-richer-descriptor
  (let [descriptors [{:command "x_y" :tool "gimp_a" :doc "" :params []}
                     {:command "x_y" :tool "gimp_b" :doc ""
                      :params [{:name "n" :wire "n" :schema :long :default 0}]}]]
    (is (= "gimp_b" (:tool (get (contract/index descriptors) "x_y"))))))

(deftest a-losing-tool-name-still-resolves
  (testing "a name this contract publishes must never answer `unknown command`"
    (is (some? (catalog/descriptor "gimp_check_server")))))

;; =============================================================================
;; The additions the reference server never exposed
;; =============================================================================

(deftest the-hand-maintained-additions-are-present
  (testing "found by the generator's cross-check: the plugin handles these, the Python server never sent them"
    (is (some? (catalog/descriptor "check_server")))
    (is (some? (catalog/descriptor "restart_server")))))

;; =============================================================================
;; Search
;; =============================================================================

(deftest search-finds-by-name-and-by-description
  (is (seq (catalog/search "layer")))
  (is (seq (catalog/search "blur")))
  (is (empty? (catalog/search "zzzznotacommand"))))

(deftest command-names-are-sorted-for-a-stable-tool-schema
  (let [names (catalog/command-names)]
    (is (= names (sort names)))))
